/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ibh.safepassword.gui;

import com.ibh.safepassword.bl.BusinessLogic;
import com.ibh.safepassword.dal.AuthInfo;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.util.ResourceBundle;

/**
 *
 * @author ihorvath
 */
public class AuthInfoDialog extends javax.swing.JDialog {

 
  /**
   * Creates new form AuthInfoDialog
   */
  public AuthInfoDialog(java.awt.Frame parent, boolean modal, BusinessLogic bl, int authid, int maxshowtime) {
    super(parent, modal);
    initComponents();
    
    AuthInfo ai = bl.getAuthRepos().GetAuthInfo(authid);
    
    setTitle(getTitle() + " - " + ai.getTitle());
    
    txtUserName.setText(ai.getUsername());
    txtPassword.setText(ai.getPwdClear());
    
    ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/ibh/safepassword/gui/Bundle"); // NOI18N
    cmdClose.setText(String.format("%s (%s)", bundle.getString("AuthInfoDialog.cmdClose.text"), maxshowtime));

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    lblUserName = new javax.swing.JLabel();
    lblPassword = new javax.swing.JLabel();
    txtUserName = new javax.swing.JPasswordField();
    txtPassword = new javax.swing.JPasswordField();
    cmdCopyUserName = new javax.swing.JButton();
    cmdCopyPwd = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    cmdClose = new javax.swing.JButton();
    cmdShowHide = new javax.swing.JToggleButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/ibh/safepassword/gui/Bundle"); // NOI18N
    setTitle(bundle.getString("AuthInfoDialog.title")); // NOI18N
    getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

    lblUserName.setText(bundle.getString("AuthInfoDialog.lblUserName.text")); // NOI18N

    lblPassword.setText(bundle.getString("AuthInfoDialog.lblPassword.text")); // NOI18N

    txtUserName.setEditable(false);

    txtPassword.setEditable(false);

    cmdCopyUserName.setText(bundle.getString("AuthInfoDialog.cmdCopyUserName.text")); // NOI18N
    cmdCopyUserName.setToolTipText(bundle.getString("AuthInfoDialog.cmdCopyUserName.toolTipText")); // NOI18N
    cmdCopyUserName.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmdCopyUserNameActionPerformed(evt);
      }
    });

    cmdCopyPwd.setText(bundle.getString("AuthInfoDialog.cmdCopyPwd.text")); // NOI18N
    cmdCopyPwd.setToolTipText(bundle.getString("AuthInfoDialog.cmdCopyPwd.toolTipText")); // NOI18N
    cmdCopyPwd.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmdCopyPwdActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblUserName)
          .addComponent(lblPassword))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
          .addComponent(txtUserName))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(cmdCopyUserName)
          .addComponent(cmdCopyPwd))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblUserName)
          .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(cmdCopyUserName))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblPassword)
          .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(cmdCopyPwd))
        .addContainerGap())
    );

    getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

    cmdClose.setText(bundle.getString("AuthInfoDialog.cmdClose.text")); // NOI18N
    cmdClose.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmdCloseActionPerformed(evt);
      }
    });

    cmdShowHide.setText(bundle.getString("AuthInfoDialog.cmdShowHide.text")); // NOI18N
    cmdShowHide.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmdShowHideActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(cmdShowHide)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cmdClose, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cmdClose)
          .addComponent(cmdShowHide))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed
    this.dispose();
  }//GEN-LAST:event_cmdCloseActionPerformed

  private void cmdCopyUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCopyUserNameActionPerformed
    char[] uname = txtUserName.getPassword();
    StringSelection unamesel = new StringSelection(String.valueOf(uname));
    Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
    clpbrd.setContents(unamesel, null);
  }//GEN-LAST:event_cmdCopyUserNameActionPerformed

  private void cmdCopyPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCopyPwdActionPerformed
    char[] pwd = txtPassword.getPassword();
    StringSelection unamesel = new StringSelection(String.valueOf(pwd));
    Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
    clpbrd.setContents(unamesel, null);
  }//GEN-LAST:event_cmdCopyPwdActionPerformed

  private void cmdShowHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdShowHideActionPerformed
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/ibh/safepassword/gui/Bundle"); // NOI18N
    if (!cmdShowHide.isSelected()) {
      cmdShowHide.setText(bundle.getString("AuthInfoDialog.cmdShowHide.text"));
      txtUserName.setEchoChar('*');
      txtPassword.setEchoChar('*');
    }
    else {
      cmdShowHide.setText(bundle.getString("AuthInfoDialog.cmdShowHide_Hide.text"));
      txtUserName.setEchoChar((char)0);
      txtPassword.setEchoChar((char)0);
    }
    this.pack();
  }//GEN-LAST:event_cmdShowHideActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton cmdClose;
  private javax.swing.JButton cmdCopyPwd;
  private javax.swing.JButton cmdCopyUserName;
  private javax.swing.JToggleButton cmdShowHide;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JLabel lblPassword;
  private javax.swing.JLabel lblUserName;
  private javax.swing.JPasswordField txtPassword;
  private javax.swing.JPasswordField txtUserName;
  // End of variables declaration//GEN-END:variables
}
